### ISSUE TITLE
Cache is not lazy loaded?

### ISSUE THREAD

**Issue by rvanlaak** [twigphp/twig-cache-extension#4]
The configured caching service seems to get requested on container build. As result of that, we have to override our caching service for our CI environment because

* The CI build process that's doing composer install builds the container. External services (e.g. Redis, ElasticSearch, MySQL) in CI build processes get connected to the box after the build step during the deploy step.
* We use Redis as external PSR-6 caching layer, so it would connect to Redis when the related cache provider is requested from the container
* The CI deploy step does deliver a read-only box to it's final location, so calling composer install after build is not possible.

So, the caching service should get loaded lazily, as it is not used during the build of the container. How would it be possible to do this? Maybe add a lazy factory in between?

**Comment by stof** [comment]
This could be implemented by moving the cache provider itself to a Twig runtime instead of having the cache injected in the extension itself. this way, instantiating the extension would not require instantiating the cache provider (the cache provider would be necessary only when rendering templates, not when compiling them). The Twig runtime system is precisely meant to lazy-load dependencies.
This would require a BC break though, as it would change the way the extension is registered.

As an immediate solution, this can be implemented with a lazy-loading CacheProvider, which would lazy-load another CacheProvider (the actual one) on usage. The compilation will not use the cache provider, and so will not trigger the lazy-loading.

**Comment by fabpot** [comment]
Done in https://github.com/twigphp/Twig/pull/3459
